[[main]]
name = "Blog"
url = "/posts/"
weight = 1

[[main]]
name = "Projects"
url = "/projects/"
weight = 2

[[main]]
name = "About"
url = "/about/"
weight = 3

[[main]]
name = "Search"
url = "/search/"
weight = 4
